import {
    GrAchievement,
    GrAdobeCreativeCloud,
    GrAggregate,
    GrAssistListening,
    GrDocumentConfig,
    GrGroup,
    GrSync,
} from 'react-icons/gr';

export const subServiceDetails = [
    {
        serviceId: 'civil-litigation',
        services: [
            {
                id: 'civil-litigation',
                title: 'Litigation',
                description: 'Expert legal representation in civil disputes.',
                slug: 'litigation',
                fileId: '1_6mNXJ8YvAqiROG2LdR51yb4kDJp6bgJ',
                icon: GrGroup,
            },
            {
                id: 'civil-litigation',
                title: 'General Litigation',
                description: 'Comprehensive support for various litigation matters.',
                slug: 'general-litigation',
                fileId: '1_2umSariBGWQ-mlOpezNBVrFjJbFclc3',
                icon: GrAssistListening,
            },
            {
                id: 'civil-litigation',
                title: 'LANDLORDS & TENANTS: RESIDENTIAL',
                description: 'Guidance on residential landlord-tenant disputes.',
                slug: 'residential-litigation',
                fileId: '1_1_A08JdJyGXknqr-2m--hwv3FycfFtc',
                icon: GrGroup,
            },
            {
                id: 'civil-litigation',
                title: 'LANDLORD & TENANTS – COMMERCIAL',
                description: 'Legal assistance for commercial landlord-tenant issues.',
                slug: 'commercial-litigation',
                fileId: '1_0N2L1fmowVB4w6xzbdLjt8QviMJLuOO',
                icon: GrSync,
            },
            {
                id: 'civil-litigation',
                title: 'PRIVATE CLIENT & PROBATE',
                description: 'Support for estate planning and probate matters.',
                slug: 'probate-litigation',
                fileId: '1ZvU6A2SVxckFlE4zGXEpjsOde_wPgUBn',
                icon: GrAggregate,
            },
            {
                id: 'civil-litigation',
                title: 'INSOLVENCY & BANKRUPCY',
                description: 'Expert advice on insolvency and bankruptcy proceedings.',
                slug: 'insolvency-bankruptcy-litigation',
                fileId: '1ZuVO7EEZzBju2iXG9N_QeosQsuiAAmea',
                icon: GrDocumentConfig,
            },
            {
                id: 'civil-litigation',
                title: 'MONEY CLAIMS & DEBT RECOVERY',
                description: 'Effective strategies for recovering debts and claims.',
                slug: 'money-claims-debt-litigation',
                fileId: '1ZruiqWuZGOgzfVVW7zGZSKLd5ucnhkzU',
                icon: GrAchievement,
            },
        ],
    },
    {
        serviceId: 'family-service',
        services: [
            {
                id: 'family-01',
                title: 'Family and Children',
                description: 'Dedicated legal support for your litigation needs.',
                slug: 'family-children-service',
                fileId: '1_nzyyvLFt1iPrEg_VR30sVXO69HyIVmA',
                icon: GrGroup,
            },
            {
                id: 'family-02',
                title: 'Divorce and Separation',
                description: 'Professional representation in civil litigation cases.',
                slug: 'divorce-separation',
                fileId: '1_neOkvNcqd90EQ3cKwXLhatYR3j-MkPd',
                icon: GrAssistListening,
            },
            {
                id: 'family-03',
                title: 'Domestic Violence and Abuse: Understanding Your Rights Under English Law',
                description: 'Skilled advocacy in various litigation scenarios.',
                slug: 'violence-abuse',
                fileId: '1_iK_olYEZKCK5YI4KggDwYKeXF0V62yC',
                icon: GrAggregate,
            },

            {
                id: 'family-04',
                title: 'Child Arrangements: Understanding Your Rights Under English Law',
                description: 'Tailored legal solutions for your litigation challenges.',
                slug: 'child-arrangements',
                fileId: '1_h0laeDge2DjRdo7ZKb0ARWtDOShrZMZ',
                icon: GrAdobeCreativeCloud,
            },
            {
                id: 'family-05',
                title: 'Financial Orders Following Divorce: Understanding Your Rights Under English Law.',
                description: 'Financial Orders Following Divorce: Understanding Your Rights Under English Law.',
                slug: 'financial-orders',
                fileId: '1_fPH_6SKI2epZdXzNBHElAr_mnXZ2UoH',
                icon: GrAchievement,
            },
            {
                id: 'family-06',
                title: 'Capital Asset Division Following Divorce: Understanding Your Rights Under English Law',
                description: 'Focused legal strategies for successful litigation outcomes.',
                slug: 'litigation-focused-strategies',
                fileId: '1_cqG3cQABRVH6iuSaPnSZr3V99lzOjOd',
                icon: GrDocumentConfig,
            },
            {
                id: 'family-07',
                title: 'Care Proceedings',
                description: 'Your trusted partner in navigating litigation processes.',
                slug: 'litigation-trusted-partner',
                fileId: '1_cbOaAeA9S5AgKQrhe9d1u4AZhpjHMRF',
                icon: GrSync,
            },
        ],
    },
    {
        serviceId: 'medical-negligence',
        services: [
            {
                id: 'mn-01',
                title: 'MEDICAL NEGLIGENCE',
                description: 'Expert legal guidance for medical negligence cases.',
                slug: 'medical-negligence-expert-guidance',
                fileId: '1acOoSeC0v89rkLKaHpf-E0ZjKMd_Gvzj',
                icon: GrGroup,
            },
            {
                id: 'mn-02',
                title: 'CATASTROPHIC INJURIES',
                description: 'Comprehensive legal support for catastrophic injuries.',
                slug: 'catastrophic-injuries-comprehensive-support',
                fileId: '1aMf1WKOWXrAuGVW3y233uSrjiAKAPAWP',
                icon: GrGroup,
            },
            {
                id: 'mn-03',
                title: 'ANAESTHETIC INJURIES',
                description: 'Specialized legal representation for anaesthetic injuries.',
                slug: 'anaesthetic-injuries-specialized-representation',
                fileId: '1aE1J7BfiYFKMn-GP_Hkp_p5HLchRH-Yo',
                icon: GrGroup,
            },
            {
                id: 'mn-04',
                title: 'SURGICAL NEGLIGENCE',
                description: 'Dedicated legal assistance for surgical negligence cases.',
                slug: 'surgical-negligence-dedicated-assistance',
                fileId: '1aAm-uecUVyTESsno-xtVa-v2SFL4dIXE',
                icon: GrGroup,
            },
            {
                id: 'mn-05',
                title: 'MISSED, DELAYED, AND WRONGFUL DIAGNOSIS',
                description: 'Proven legal strategies for missed, delayed, and wrongful diagnosis cases.',
                slug: 'missed-delayed-wrongful-diagnosis-proven-strategies',
                fileId: '1bVmjNyJo4B_PfnAOWy1mtqlFrysrEdyP',
                icon: GrGroup,
            },
            {
                id: 'mn-06',
                title: 'BIRTH RELATED INJURIES',
                description: 'Your trusted partner in navigating birth related injuries litigation.',
                slug: 'birth-related-injuries-trusted-partner',
                fileId: '1bVI373dqWNdYpi8Ywn7vJoow26_J33mO',
                icon: GrGroup,
            },
            {
                id: 'mn-07',
                title: 'GYNAECOLOGICAL INJURIES',
                description: 'Focused legal support for gynaecological injuries cases.',
                slug: 'gynaecological-injuries-focused-support',
                fileId: '1bDsuDDul8w4y4mpqXJwShA6VD2hPKIMi',
                icon: GrGroup,
            },
            {
                id: 'mn-08',
                title: 'PRODUCT LIABILITY CLAIMS (MEDICAL DEVICES)',
                description: 'Expert legal representation for product liability claims related to medical devices.',
                slug: 'product-liability-claims-medical-devices',
                fileId: '1b0prTCIt2Ii6d8Viwz0WgZSNsMaZIx8W',
                icon: GrGroup,
            },
            {
                id: 'mn-09',
                title: 'PLASTIC/COSMETIC SURGERY NEGLIGENCE',
                description: 'Expert legal representation for plastic/cosmetic surgery negligence cases.',
                slug: 'plastic-cosmetic-surgery-negligence',
                fileId: '1aqHWtWT0WRzW8oPfHaMxjNGP59KHVoDA',
                icon: GrGroup,
            },
            {
                id: 'mn-10',
                title: 'CONSENT TO TREATMENT',
                description: 'Expert legal representation for consent to treatment cases.',
                slug: 'consent-to-treatment',
                fileId: '1abyCE8l9VDiRi2r-0pC1a6JVubnlyywP',
                icon: GrGroup,
            },
            {
                id: 'mn-11',
                title: 'GP NEGLIGENCE',
                description: 'Expert legal representation for GP negligence cases.',
                slug: 'gp-negligence',
                fileId: '1aWeLqc9Qb6yCQjEBdWKr4sbIex0Acbug',
                icon: GrGroup,
            },
            {
                id: 'mn-12',
                title: 'DENTAL NEGLIGENCE',
                description: 'Expert legal representation for dental negligence cases.',
                slug: 'dental-negligence',
                fileId: '1aRHuau5O-6lf3TMdO4DcSqEW0bwCcs41',
                icon: GrGroup,
            },
        ],
    },
    {
        serviceId: 'personal-injury',
        services: [
            {
                id: 'pi-01',
                title: 'PERSONAL INJURY',
                description: 'Expert legal representation for personal injury cases.',
                slug: 'personal-injury-aid',
                fileId: '1crm_8hvypMqS44NkCV1ad9X1jByoJAWb',
                icon: GrGroup,
            },
            {
                id: 'pi-02',
                title: 'Road Traffic Accidents',
                description: 'Comprehensive support for road traffic accident claims.',
                slug: 'traffic-accidents',
                fileId: '1cqckT1528NvL20u4Y_ojbl2dRLBOzZdk',
                icon: GrGroup,
            },
            {
                id: 'pi-03',
                title: 'Accidents at Work',
                description: 'Specialized legal guidance for workplace accidents.',
                slug: 'work-accidents',
                fileId: '1cp8eZlw1rR0EdqHRHCVQ-ZZXz8JMI8Ey',
                icon: GrGroup,
            },
            {
                id: 'pi-04',
                title: 'Occupational Stress Claims',
                description: 'Strategic legal representation for occupational stress claims.',
                slug: 'stress-claims',
                fileId: '1cWUTCVoA5JrD0UN12P5cR-9KxgQqWwlY',
                icon: GrGroup,
            },
            {
                id: 'pi-05',
                title: 'Slips, Trips, and Falls',
                description: 'Focused legal support for slips, trips, and falls cases.',
                slug: 'slips-trips',
                fileId: '1cPperjfWZEOmXcZWlSXfLA8DCCloIKIw',
            },
            {
                id: 'pi-06',
                title: 'Product Liability Claims',
                description: 'Expert legal representation for product liability claims.',
                slug: 'product-claims',
                fileId: '1cNe1jWV5h8HUmrTjQmlcSfJVrNeW2dr7',
                icon: GrGroup,
            },
            {
                id: 'pi-07',
                title: 'Fatal Accident Claims',
                description: 'Compassionate legal support for fatal accident claims.',
                slug: 'fatal-accidents',
                fileId: '1cF8FB2GIGLSdGkDPJcPnwGCeHocqBp0n',
                icon: GrGroup,
            },
        ],
    },
    {
        serviceId: 'immigration',
        services: [
            {
                id: 'im-01',
                title: 'Administrative Review',
                description: 'Comprehensive legal guidance for administrative review processes.',
                slug: 'administrative-review',
                fileId: '1a7v2pYP7q7ECnGKifwIfVElyjtJoS32N',
                icon: GrGroup,
            },
            {
                id: 'im-02',
                title: 'Business Immigration',
                description: 'Expert legal support for business immigration matters.',
                slug: 'business-immigration',
                fileId: '1a78owkfWpC-ZU5-JygZ0bEXyyLvFziyG',
                icon: GrGroup,
            },
            {
                id: 'im-03',
                title: 'Family Visa',
                description: 'Personalized legal assistance for family visa applications.',
                slug: 'family-visa',
                fileId: '1a6UNv2eH-mtVzvMVs1Va6j35lyElGcdz',
                icon: GrGroup,
            },
            {
                id: 'im-04',
                title: 'Funding Options for Immigration Services',
                description: 'Exploring funding options for immigration services.',
                slug: 'funding-options',
                fileId: '1_wKDvgHGGCqNbHChJ7FyUfY1rko3So1Y',
                icon: GrGroup,
            },
            {
                id: 'im-05',
                title: 'Human Rights Applications, Asylum, and Immigration Appeals',
                description:
                    'Compassionate legal representation for human rights applications, asylum, and immigration appeals.',
                slug: 'human-rights-applications',
                fileId: '1_vuTkj1JUFu6leXscw5x0pOUZ8wOJ-Qp',
                icon: GrGroup,
            },
            {
                id: 'im-06',
                title: 'Immigration (Main Page)',
                description: 'Overview of immigration services and legal support.',
                slug: 'immigration-main-page',
                fileId: '1_rXiLIp5JW3x6oKO4zgjgj3aaXwWBdXR',
                icon: GrGroup,
            },
            {
                id: 'im-07',
                title: 'Individual Immigration',
                description: 'Tailored legal solutions for individual immigration needs.',
                slug: 'individual-immigration',
                fileId: '1_rDXcdfSUwTgAKncQ9r4cBzsdD0aLul7',
                icon: GrGroup,
            },
            {
                id: 'im-08',
                title: 'Judicial Review',
                description: 'Expert legal representation for judicial review proceedings.',
                slug: 'judicial-review',
                fileId: '1ad0peQDm6KmsACF38ZLovkSL0svOkRzY',
                icon: GrGroup,
            },
        ],
    },
    {
        serviceId: 'housing-legal-aid',
        services: [
            {
                id: 'hla-01',
                title: 'HOUSING: LEGAL AID',
                description: 'Expert legal support for housing-related legal aid matters.',
                slug: 'housing-aid',
                fileId: '1a8BgJW5te8RC-_pLaV5x3nqmOG9o5Qlt',
                icon: GrGroup,
            },
        ],
    },
    {
        serviceId: 'employment',
        services: [
            {
                id: 'em-01',
                title: 'EMPLOYMENT',
                description: 'Comprehensive legal guidance for employment-related issues.',
                slug: 'employment-law',
                fileId: '1_qXgNlrutqsx6Urq5hc4cLzkzq4pVD8s',
                icon: GrGroup,
            },
        ],
    },
    {
        serviceId: 'mental-health',
        services: [
            {
                id: 'mh-01',
                title: 'Mental Health',
                description: 'Expert legal guidance for mental health issues.',
                slug: 'mental-health-aid',
                fileId: '1aqDet1dTjyhoOrLd970StDmUh7g5l0WG',
                icon: GrGroup,
            },
            {
                id: 'mh-02',
                title: 'Mental Health Detention',
                description: 'Legal support for mental health detention under Sections 2 and 3.',
                slug: 'mental-detention',
                fileId: '1ajgvaWo1FjApjBCoqY4re-WClLbYy3VC',
                icon: GrGroup,
            },
            {
                id: 'mh-03',
                title: 'Section 7 Guardianship',
                description: 'Understanding rights under Section 7 Guardianship.',
                slug: 'section-7',
                fileId: '1ag8JgT_Upng8qSolSPm0mGO4Cuh2yLDk',
                icon: GrGroup,
            },
            {
                id: 'mh-04',
                title: 'Section 17A Orders',
                description: 'Legal guidance for Section 17A Community Treatment Orders.',
                slug: 'section-17a',
                fileId: '1cDbVC9Dm0I2dpimaA2wyibbfecWenCze',
                icon: GrGroup,
            },
            {
                id: 'mh-05',
                title: 'Section 37 Powers',
                description: 'Understanding Section 37 Powers of Courts for Hospital Admission or Guardianship.',
                slug: 'section-37',
                fileId: '1cAfIOSyv_Nhmlo96_y0g-Hz61fjr8Pv9',
                icon: GrGroup,
            },
            {
                id: 'mh-06',
                title: 'Mental Health Rights',
                description: 'Understanding rights under Sections 38, 41(5), 45A, and 48.',
                slug: 'mental-rights',
                fileId: '1c5XY1X22yYzKdhf_pzXnOhNGqfFUPOsl',
                icon: GrGroup,
            },
            {
                id: 'mh-07',
                title: 'Guardianship Orders',
                description: 'Understanding rights under Section 7 Guardianship Orders.',
                slug: 'guardianship',
                fileId: '1c1VTcPeFaZzjNphrvfP7LLTp71vfmJfu',
                icon: GrGroup,
            },
            {
                id: 'mh-08',
                title: 'Challenging Detention',
                description: 'Legal support for challenging detention in hospital.',
                slug: 'challenging-detention',
                fileId: '1c-3VuTDB1WY45VH_unWIzNa4iLoMbt3s',
                icon: GrGroup,
            },
            {
                id: 'mh-09',
                title: 'Hospital Orders',
                description: 'Legal guidance for hospital orders.',
                slug: 'hospital-orders',
                fileId: '1bZCoLFnupWW1N9GLiQL2pzHOLqovVhxv',
                icon: GrGroup,
            },
            {
                id: 'mh-10',
                title: 'Community Treatment',
                description: 'Legal support for Community Treatment Orders (CTO).',
                slug: 'community-treatment',
                fileId: '1bXPVgZVFoO_uOvAO0iILNhnIk04k3ngT',
                icon: GrGroup,
            },
            {
                id: 'mh-11',
                title: 'Prison Transfers',
                description: 'Legal guidance for prison transfers under Section 47.',
                slug: 'prison-transfers',
                fileId: '1bWrCkCyoPBC-rEdIDbzAbKJvrvx91brr',
                icon: GrGroup,
            },
            {
                id: 'mh-12',
                title: 'Legal Aid Funding',
                description: 'Funding options for legal cases.',
                slug: 'legal-aid',
                fileId: '1ctOuJlppzUtb32nLgH_gFXYqbrThP2tE',
                icon: GrGroup,
            },
        ],
    },
    {
        serviceId: 'commercial-conveyancing',
        services: [
            {
                id: 'cc-01',
                title: 'COMMERCIAL CONVEYANCING',
                description: 'Specialized legal assistance for commercial property transactions and disputes.',
                slug: 'commercial-conveyancing-aid',
                fileId: '1ZqWpOF04MeuG4Ao5xcFnycOOdHTlxVcu',
                icon: GrGroup,
            },
        ],
    },
    {
        serviceId: 'crime',
        services: [
            {
                id: 'cr-01',
                title: 'Criminal Defence',
                description: 'Expert legal support for criminal cases.',
                slug: 'criminal-defence',
                fileId: '1_bpiizuhKUmcmuTH8J_NTCzIPLjMvWto',
                icon: GrGroup,
            },
            {
                id: 'cr-02',
                title: 'POLICE STATION REPRESENTATION',
                description: 'Legal representation at police stations.',
                slug: 'police-rep',
                fileId: '1_WaxWG6VSfcQOLDK8WQY3EWjuZklIF8m',
                icon: GrGroup,
            },
            {
                id: 'cr-03',
                title: 'COURT REPRESENTATION',
                description: 'Professional court representation services.',
                slug: 'court-rep',
                fileId: '1_NOMkYfLe5V4gsPMFyiDXbykTg-ACkec',
                icon: GrGroup,
            },
            {
                id: 'cr-04',
                title: 'Serious Crime Defence',
                description: 'Specialized defence for serious crimes.',
                slug: 'serious-crime',
                fileId: '1_MRfP0zCATzV3ON2jrQiwuliMeUXzF0J',
                icon: GrGroup,
            },
            {
                id: 'cr-05',
                title: 'ROAD TRAFFIC OFFENCES',
                description: 'Legal assistance for road traffic violations.',
                slug: 'traffic-offences',
                fileId: '1_Ke8sb1hhOk0l2wqpjouOd_hyAg-JLdz',
                icon: GrGroup,
            },
            {
                id: 'cr-06',
                title: 'APPEALS',
                description: 'Expert legal support for appeals.',
                slug: 'appeals',
                fileId: '1_Jk-qpYX4yjLTWyqK13i173v-66T4xll',
                icon: GrGroup,
            },
            {
                id: 'cr-07',
                title: 'ACTION AGAINST THE POLICE',
                description: 'Legal action against police misconduct.',
                slug: 'police-action',
                fileId: '1_EYeMSWBvx4ALSvesXKVU7jP3oD7cLH8',
                icon: GrGroup,
            },
            {
                id: 'cr-08',
                title: 'Guiding Principles',
                description: 'Guiding principles for legal proceedings.',
                slug: 'guiding-principles',
                fileId: '1_BwJSin8o6DKv-q0YDWslImQ7D6IbLH5',
                icon: GrGroup,
            },
        ],
    },
];
