export const subServiceDetails = [
    {
        serviceId: 'civil-litigation',
        services: [
            {
                id: 'civil-litigation',
                title: 'Litigation',
                description: 'Expert legal representation in civil disputes.',
                slug: 'litigation',
                fileId: '',
            },
            {
                id: 'civil-litigation',
                title: 'General Litigation',
                description: 'Comprehensive support for various litigation matters.',
                slug: 'general-litigation',
                fileId: '',
            },
            {
                id: 'civil-litigation',
                title: 'LANDLORDS & TENANTS: RESIDENTIAL',
                description: 'Guidance on residential landlord-tenant disputes.',
                slug: 'residential-litigation',
                fileId: '',
            },
            {
                id: 'civil-litigation',
                title: 'LANDLORD & TENANTS – COMMERCIAL',
                description: 'Legal assistance for commercial landlord-tenant issues.',
                slug: 'commercial-litigation',
                fileId: '',
            },
            {
                id: 'civil-litigation',
                title: 'PRIVATE CLIENT & PROBATE',
                description: 'Support for estate planning and probate matters.',
                slug: 'probate-litigation',
                fileId: '',
            },
            {
                id: 'civil-litigation',
                title: 'INSOLVENCY & BANKRUPCY',
                description: 'Expert advice on insolvency and bankruptcy proceedings.',
                slug: 'insolvency-bankruptcy-litigation',
                fileId: '',
            },
            {
                id: 'civil-litigation',
                title: 'MONEY CLAIMS & DEBT RECOVERY',
                description: 'Effective strategies for recovering debts and claims.',
                slug: 'money-claims-debt-litigation',
                fileId: '',
            },
        ],
    },
    {
        serviceId: 'family-service',
        services: [
            {
                id: 'family-01',
                title: 'Family and Children',
                description: 'Dedicated legal support for your litigation needs.',
                slug: 'family-children-service',
                fileId: '',
            },
            {
                id: 'family-02',
                title: 'Divorce and Separation',
                description: 'Professional representation in civil litigation cases.',
                slug: 'divorce-separation',
                fileId: '',
            },
            {
                id: 'family-03',
                title: 'Domestic Violence and Abuse: Understanding Your Rights Under English Law',
                description: 'Skilled advocacy in various litigation scenarios.',
                slug: 'violence-abuse',
                fileId: '',
            },

            {
                id: 'family-04',
                title: 'Child Arrangements: Understanding Your Rights Under English Law',
                description: 'Tailored legal solutions for your litigation challenges.',
                slug: 'child-arrangements',
                fileId: '',
            },
            {
                id: 'family-05',
                title: 'Financial Orders Following Divorce: Understanding Your Rights Under English Law.',
                description: 'Financial Orders Following Divorce: Understanding Your Rights Under English Law.',
                slug: 'financial-orders',
                fileId: '',
            },
            {
                id: 'family-06',
                title: 'Capital Asset Division Following Divorce: Understanding Your Rights Under English Law',
                description: 'Focused legal strategies for successful litigation outcomes.',
                slug: 'litigation-focused-strategies',
                fileId: '',
            },
            {
                id: 'family-07',
                title: 'Care Proceedings',
                description: 'Your trusted partner in navigating litigation processes.',
                slug: 'litigation-trusted-partner',
                fileId: '',
            },
        ],
    },
    {
        serviceId: 'medical-negligence',
        services: [
            {
                id: 'mn-01',
                title: 'MEDICAL NEGLIGENCE',
                description: 'Expert legal guidance for medical negligence cases.',
                slug: 'medical-negligence-expert-guidance',
                fileId: '',
            },
            {
                id: 'mn-02',
                title: 'CATASTROPHIC INJURIES',
                description: 'Comprehensive legal support for catastrophic injuries.',
                slug: 'catastrophic-injuries-comprehensive-support',
                fileId: '',
            },
            {
                id: 'mn-03',
                title: 'ANAESTHETIC INJURIES',
                description: 'Specialized legal representation for anaesthetic injuries.',
                slug: 'anaesthetic-injuries-specialized-representation',
                fileId: '',
            },
            {
                id: 'mn-04',
                title: 'SURGICAL NEGLIGENCE',
                description: 'Dedicated legal assistance for surgical negligence cases.',
                slug: 'surgical-negligence-dedicated-assistance',
                fileId: '',
            },
            {
                id: 'mn-05',
                title: 'MISSED, DELAYED, AND WRONGFUL DIAGNOSIS',
                description: 'Proven legal strategies for missed, delayed, and wrongful diagnosis cases.',
                slug: 'missed-delayed-wrongful-diagnosis-proven-strategies',
                fileId: '',
            },
            {
                id: 'mn-06',
                title: 'BIRTH RELATED INJURIES',
                description: 'Your trusted partner in navigating birth related injuries litigation.',
                slug: 'birth-related-injuries-trusted-partner',
                fileId: '',
            },
            {
                id: 'mn-07',
                title: 'GYNAECOLOGICAL INJURIES',
                description: 'Focused legal support for gynaecological injuries cases.',
                slug: 'gynaecological-injuries-focused-support',
                fileId: '',
            },
            {
                id: 'mn-08',
                title: 'PRODUCT LIABILITY CLAIMS (MEDICAL DEVICES)',
                description: 'Expert legal representation for product liability claims related to medical devices.',
                slug: 'product-liability-claims-medical-devices',
                fileId: '',
            },
            {
                id: 'mn-09',
                title: 'PLASTIC/COSMETIC SURGERY NEGLIGENCE',
                description: 'Expert legal representation for plastic/cosmetic surgery negligence cases.',
                slug: 'plastic-cosmetic-surgery-negligence',
                fileId: '',
            },
            {
                id: 'mn-10',
                title: 'CONSENT TO TREATMENT',
                description: 'Expert legal representation for consent to treatment cases.',
                slug: 'consent-to-treatment',
                fileId: '',
            },
            {
                id: 'mn-11',
                title: 'GP NEGLIGENCE',
                description: 'Expert legal representation for GP negligence cases.',
                slug: 'gp-negligence',
                fileId: '',
            },
            {
                id: 'mn-12',
                title: 'DENTAL NEGLIGENCE',
                description: 'Expert legal representation for dental negligence cases.',
                slug: 'dental-negligence',
                fileId: '',
            },
        ],
    },
    {
        serviceId: 'personal-injury',
        services: [
            {
                id: 'pi-01',
                title: 'PERSONAL INJURY',
                description: 'Expert legal representation for personal injury cases.',
                slug: 'personal-injury-aid',
                fileId: '',
            },
            {
                id: 'pi-02',
                title: 'Road Traffic Accidents',
                description: 'Comprehensive support for road traffic accident claims.',
                slug: 'traffic-accidents',
                fileId: '',
            },
            {
                id: 'pi-03',
                title: 'Accidents at Work',
                description: 'Specialized legal guidance for workplace accidents.',
                slug: 'work-accidents',
                fileId: '',
            },
            {
                id: 'pi-04',
                title: 'Occupational Stress Claims',
                description: 'Strategic legal representation for occupational stress claims.',
                slug: 'stress-claims',
                fileId: '',
            },
            {
                id: 'pi-05',
                title: 'Slips, Trips, and Falls',
                description: 'Focused legal support for slips, trips, and falls cases.',
                slug: 'slips-trips',
                fileId: '',
            },
            {
                id: 'pi-06',
                title: 'Product Liability Claims',
                description: 'Expert legal representation for product liability claims.',
                slug: 'product-claims',
                fileId: '',
            },
            {
                id: 'pi-07',
                title: 'Fatal Accident Claims',
                description: 'Compassionate legal support for fatal accident claims.',
                slug: 'fatal-accidents',
                fileId: '',
            },
        ],
    },
    {
        serviceId: 'immigration',
        services: [
            {
                id: 'im-01',
                title: 'Administrative Review',
                description: 'Comprehensive legal guidance for administrative review processes.',
                slug: 'administrative-review',
                fileId: 'immigration/administrative-review',
            },
            {
                id: 'im-02',
                title: 'Business Immigration',
                description: 'Expert legal support for business immigration matters.',
                slug: 'business-immigration',
                fileId: 'immigration/business-immigration',
            },
            {
                id: 'im-03',
                title: 'Family Visa',
                description: 'Personalized legal assistance for family visa applications.',
                slug: 'family-visa',
                fileId: 'immigration/family-visa',
            },
            {
                id: 'im-04',
                title: 'Funding Options for Immigration Services',
                description: 'Exploring funding options for immigration services.',
                slug: 'funding-options',
                fileId: 'immigration/funding-options',
            },
            {
                id: 'im-05',
                title: 'Human Rights Applications, Asylum, and Immigration Appeals',
                description:
                    'Compassionate legal representation for human rights applications, asylum, and immigration appeals.',
                slug: 'human-rights-applications',
                fileId: 'immigration/human-rights-applications',
            },
            {
                id: 'im-06',
                title: 'Immigration (Main Page)',
                description: 'Overview of immigration services and legal support.',
                slug: 'immigration-main-page',
                fileId: 'immigration/immigration-main-page',
            },
            {
                id: 'im-07',
                title: 'Individual Immigration',
                description: 'Tailored legal solutions for individual immigration needs.',
                slug: 'individual-immigration',
                fileId: 'immigration/individual-immigration',
            },
            {
                id: 'im-08',
                title: 'Judicial Review',
                description: 'Expert legal representation for judicial review proceedings.',
                slug: 'judicial-review',
                fileId: 'immigration/judicial-review',
            },
        ],
    },
    {
        serviceId: 'housing-legal-aid',
        services: [
            {
                id: 'hla-01',
                title: 'HOUSING: LEGAL AID',
                description: 'Expert legal support for housing-related legal aid matters.',
                slug: 'housing-aid',
                fileId: 'housing-legal-aid/housing-aid',
            },
        ],
    },
    {
        serviceId: 'employment',
        services: [
            {
                id: 'em-01',
                title: 'EMPLOYMENT',
                description: 'Comprehensive legal guidance for employment-related issues.',
                slug: 'employment-law',
                fileId: 'employment/employment-law',
            },
        ],
    },
    {
        serviceId: 'mental-health',
        services: [
            {
                id: 'mh-01',
                title: 'Mental Health',
                description: 'Expert legal guidance for mental health issues.',
                slug: 'mental-health-aid',
                fileId: 'mental-health/mental-health-aid',
            },
            {
                id: 'mh-02',
                title: 'Mental Health Detention',
                description: 'Legal support for mental health detention under Sections 2 and 3.',
                slug: 'mental-detention',
                fileId: 'mental-health/mental-detention',
            },
            {
                id: 'mh-03',
                title: 'Section 7 Guardianship',
                description: 'Understanding rights under Section 7 Guardianship.',
                slug: 'section-7',
                fileId: 'mental-health/section-7',
            },
            {
                id: 'mh-04',
                title: 'Section 17A Orders',
                description: 'Legal guidance for Section 17A Community Treatment Orders.',
                slug: 'section-17a',
                fileId: 'mental-health/section-17a',
            },
            {
                id: 'mh-05',
                title: 'Section 37 Powers',
                description: 'Understanding Section 37 Powers of Courts for Hospital Admission or Guardianship.',
                slug: 'section-37',
                fileId: 'mental-health/section-37',
            },
            {
                id: 'mh-06',
                title: 'Mental Health Rights',
                description: 'Understanding rights under Sections 38, 41(5), 45A, and 48.',
                slug: 'mental-rights',
                fileId: 'mental-health/mental-rights',
            },
            {
                id: 'mh-07',
                title: 'Guardianship Orders',
                description: 'Understanding rights under Section 7 Guardianship Orders.',
                slug: 'guardianship',
                fileId: 'mental-health/guardianship',
            },
            {
                id: 'mh-08',
                title: 'Challenging Detention',
                description: 'Legal support for challenging detention in hospital.',
                slug: 'challenging-detention',
                fileId: 'mental-health/challenging-detention',
            },
            {
                id: 'mh-09',
                title: 'Hospital Orders',
                description: 'Legal guidance for hospital orders.',
                slug: 'hospital-orders',
                fileId: 'mental-health/hospital-orders',
            },
            {
                id: 'mh-10',
                title: 'Community Treatment',
                description: 'Legal support for Community Treatment Orders (CTO).',
                slug: 'community-treatment',
                fileId: 'mental-health/community-treatment',
            },
            {
                id: 'mh-11',
                title: 'Prison Transfers',
                description: 'Legal guidance for prison transfers under Section 47.',
                slug: 'prison-transfers',
                fileId: 'mental-health/prison-transfers',
            },
            {
                id: 'mh-12',
                title: 'Legal Aid Funding',
                description: 'Funding options for legal cases.',
                slug: 'legal-aid',
                fileId: 'mental-health/legal-aid',
            },
        ],
    },
    {
        serviceId: 'commercial-conveyancing',
        services: [
            {
                id: 'cc-01',
                title: 'COMMERCIAL CONVEYANCING',
                description: 'Specialized legal assistance for commercial property transactions and disputes.',
                slug: 'commercial-conveyancing-aid',
                fileId: 'commercial-conveyancing/commercial-conveyancing-aid',
            },
        ],
    },
    {
        serviceId: 'crime',
        services: [
            {
                id: 'cr-01',
                title: 'Criminal Defence',
                description: 'Expert legal support for criminal cases.',
                slug: 'criminal-defence',
                fileId: '1_bpiizuhKUmcmuTH8J_NTCzIPLjMvWto',
            },
            {
                id: 'cr-02',
                title: 'POLICE STATION REPRESENTATION',
                description: 'Legal representation at police stations.',
                slug: 'police-rep',
                fileId: '1_WaxWG6VSfcQOLDK8WQY3EWjuZklIF8m',
            },
            {
                id: 'cr-03',
                title: 'COURT REPRESENTATION',
                description: 'Professional court representation services.',
                slug: 'court-rep',
                fileId: '1_NOMkYfLe5V4gsPMFyiDXbykTg-ACkec',
            },
            {
                id: 'cr-04',
                title: 'Serious Crime Defence',
                description: 'Specialized defence for serious crimes.',
                slug: 'serious-crime',
                fileId: '1_MRfP0zCATzV3ON2jrQiwuliMeUXzF0J',
            },
            {
                id: 'cr-05',
                title: 'ROAD TRAFFIC OFFENCES',
                description: 'Legal assistance for road traffic violations.',
                slug: 'traffic-offences',
                fileId: '1_Ke8sb1hhOk0l2wqpjouOd_hyAg-JLdz',
            },
            {
                id: 'cr-06',
                title: 'APPEALS',
                description: 'Expert legal support for appeals.',
                slug: 'appeals',
                fileId: '1_Jk-qpYX4yjLTWyqK13i173v-66T4xll',
            },
            {
                id: 'cr-07',
                title: 'ACTION AGAINST THE POLICE',
                description: 'Legal action against police misconduct.',
                slug: 'police-action',
                fileId: '1_EYeMSWBvx4ALSvesXKVU7jP3oD7cLH8',
            },
            {
                id: 'cr-08',
                title: 'Guiding Principles',
                description: 'Guiding principles for legal proceedings.',
                slug: 'guiding-principles',
                fileId: '1_BwJSin8o6DKv-q0YDWslImQ7D6IbLH5',
            },
        ],
    },
];
